
spring:
  application:
  name: springboot-backend
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-Auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect